build: copy-pdfs
    mkdocs build --site-dir ../target/docs

serve: copy-pdfs
    mkdocs serve

@copy-pdfs:
    cp whitepapers/Semi-structured\ Document\ Feature\ Extraction/misc/main.pdf docs/resources/feature-extraction.pdf
    cp whitepapers/Table\ Layout\ Regular\ Expression\ -\ Layex/misc/main.pdf docs/resources/layex.pdf
