on:
    workflow_call:
        inputs:
            service:
                required: true
                type: string
        secrets:
            OPENAI_KEY:
                required: true

jobs:
    maven-test:
        runs-on: [ubuntu-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v4
              with:
                  java-version: 17
                  distribution: "temurin"

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}

            - name: Installing local dependencies
              run: mvn -U -B clean initialize --projects :${{ inputs.service }} --also-make

            - name: Test project
              run: mvn -U -B -Dtest=UnitTestSuite -Dsurefire.failIfNoSpecifiedTests=false test --projects :${{ inputs.service }} --also-make
              env:
                  OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
